export const FETCH_USER_TABLE = "FETCH_USER_TABLE";
export const FETCH_TRANSACTION_TABLE = "FETCH_TRANSACTION_TABLE";
export const POST_TRANSACTION = "POST_TRANSACTION";
export const SERVER_MSG = "SERVER_MSG";
